// skeletons/python-react-modular-monolith-docker-compose/client/src/features/catalog/CatalogList.tsx
import { useQuery } from "@tanstack/react-query";

import { fetchProducts } from "./api";

export function CatalogList() {
  const { data, isPending, isError, error } = useQuery({
    queryKey: ["products"],
    queryFn: fetchProducts,
  });

  if (isPending) {
    return <p className="text-gray-500">Loading products…</p>;
  }
  if (isError) {
    return <p className="text-red-600">{error.message}</p>;
  }
  return (
    <div>
      <ul className="divide-y rounded-lg border">
        {data.data.map((product) => (
          <li key={product.id} className="flex items-center justify-between p-4">
            <span>{product.name}</span>
            <span className="font-mono text-sm text-gray-500">{product.sku}</span>
          </li>
        ))}
      </ul>
      <p className="mt-2 text-sm text-gray-500">{data.meta.totalCount} product(s)</p>
    </div>
  );
}

// skeletons/dotnet-angular-modular-monolith-docker-compose/client/src/app/features/catalog/catalog-list.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, inject, signal } from '@angular/core';

export type Product = {
  id: string;
  sku: string;
  name: string;
  createdAt: string; // ISO 8601
};

export type ListEnvelope<T> = {
  data: T;
  meta: { totalCount: number };
};

@Component({
  selector: 'app-catalog-list',
  templateUrl: './catalog-list.component.html',
  styles: [],
})
export class CatalogListComponent {
  private readonly http = inject(HttpClient);

  // Signals own component state; RxJS is used only for the HTTP call
  // (adrs/angular/signals-state.md)
  readonly products = signal<Product[]>([]);
  readonly totalCount = signal(0);
  readonly loading = signal(true);
  readonly error = signal<string | null>(null);

  constructor() {
    this.http.get<ListEnvelope<Product[]>>('/api/products').subscribe({
      next: (envelope) => {
        this.products.set(envelope.data);
        this.totalCount.set(envelope.meta.totalCount);
        this.loading.set(false);
      },
      error: () => {
        this.error.set('Failed to load products.');
        this.loading.set(false);
      },
    });
  }
}

@if (loading()) {
  <p class="text-gray-500">Loading products…</p>
} @else if (error()) {
  <p class="text-red-600">{{ error() }}</p>
} @else {
  <ul class="divide-y rounded-lg border">
    @for (product of products(); track product.id) {
      <li class="flex items-center justify-between p-4">
        <span>{{ product.name }}</span>
        <span class="font-mono text-sm text-gray-500">{{ product.sku }}</span>
      </li>
    } @empty {
      <li class="p-4 text-gray-500">No products yet.</li>
    }
  </ul>
  <p class="mt-2 text-sm text-gray-500">{{ totalCount() }} product(s)</p>
}
